// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lift_games_database.data;

#nullable disable

namespace lift_games_database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231220194823_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lift_games_database.games", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("about")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("download")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gamename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mainimg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("miniimg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("screenshot1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("screenshot2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
